[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://blog.bullocksshop.com/*"
  to = "/blog/index.html"
  status = 200

[[redirects]]
  from = "https://shop.bullocksshop.com/*"
  to = "/shop/index.html"
  status = 200

[[redirects]]
  from = "https://about.bullocksshop.com/*"
  to = "/about/index.html"
  status = 200

[[redirects]]
  from = "https://contact.bullocksshop.com/*"
  to = "/contact/index.html"
  status = 200

[[redirects]]
  from = "https://privacy.bullocksshop.com/*"
  to = "/privacy/index.html"
  status = 200

[[redirects]]
  from = "https://terms.bullocksshop.com/*"
  to = "/terms/index.html"
  status = 200

[[redirects]]
  from = "https://cart.bullocksshop.com/*"
  to = "/cart/index.html"
  status = 200

[[redirects]]
  from = "https://compliance.bullocksshop.com/*"
  to = "/compliance/index.html"
  status = 200

[[redirects]]
  from = "https://home.bullocksshop.com/*"
  to = "/home/index.html"
  status = 200

[[redirects]]
  from = "https://storefront.bullocksshop.com/*"
  to = "/storefront/index.html"
  status = 200
